name: 15 - Working with Matrices
on:
    workflow_dispatch:
jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os: 
                    - ubuntu-latest 
                    - windows-latest
                include:
                    - os: ubuntuu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        runs-on: ${{ matrix.os }}
        steps:
            - name: Setup node
              uses: actions/setup-node@v4
              with: 
                node-version: ${{ matrix.node-version }}
            - name: Fail experitmental
              if: matrix.tag == 'experimental'
              run: exit 1
            - name: Perform some tests
              run: |
                echo "Running tests on ${{ matrix.os }} with Node ${{ matrix.node-version }}"
                sleep 10
            - name: Upload test results
              run: echo "Uploading test results"

            